name: Docker

on:
  push:
    tags: ["v*.*.*"]
  
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: tvspgm/cms-ui
      CLUSTER_NAME: tvsmazpartspgmaksdev01
      RESOURCE_GROUP: tvsmazpartspgmrsgdev01

    steps:      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.AZ_UR }}
          password: ${{ secrets.AZ_PD }}
      
      - name: Build and push
        run: |
          docker build . -t ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Login to Azure
        id: azure-login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'default'
          action: deploy
          manifests: 
            k8s/cms-ui.yml                   
          images: |
            tvsmazpartspgmacrdev01.azurecr.io/tvspgm/cms-ui:${{ github.sha }}
          imagepullsecrets: 'tvspgm-acr'
            
