name: Docker

on: [push]
  
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: fastifyrestlearn
      CLUSTER_NAME: luffy-k8s
      RESOURCE_NAME: deletethislater

    steps:      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install aks
        uses: azure/setup-kubectl@v3
        with:
          version: '1.24.9' 
        id: install    
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.AZ_UR }}
          password: ${{ secrets.AZ_PD }}
      
      - name: Build and push
        run:
          docker build -t ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      
      - name: set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with: 
          creds: ${{ Secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP}}

      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'default'
          action: deploy
          manifests:
            k8s-dep.yml
          images: '${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'
          imagepullsecrets: 'hakuna-acr'
            
